# Leaflet integrations in Jupyter notebooks for interactive maps

In [5]:
from ipyleaflet import *

In [6]:
# example map
m = Map(center=(52, 10), zoom=8, basemap=basemaps.Esri.DeLorme)
m

Map(basemap={'url': 'http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/DeLorme_World_Base_Map/MapSâ€¦

# Load collected data

Data was collected using the Google Places API and saved in two batches to .csv files.

In [7]:
import pandas as pd
places_df1 = pd.read_csv('data/places_include_distance.csv')
places_df2 = pd.read_csv('data/places_include_distance2.csv')
places_df = pd.concat([places_df1, places_df2], ignore_index=True)
print(places_df.columns)
places_df.describe()

Index(['country', 'geometry', 'icon', 'id', 'ikea_address', 'ikea_location',
       'ikea_place_id', 'ikea_rating', 'ikea_user_ratings_total', 'name',
       'opening_hours', 'photos', 'place_id', 'plus_code', 'price_level',
       'rating', 'reference', 'scope', 'type', 'types', 'user_ratings_total',
       'vicinity', 'distance_to_ikea', 'duration_to_ikea'],
      dtype='object')

,ikea_rating,ikea_user_ratings_total,price_level,rating,user_ratings_total,distance_to_ikea,duration_to_ikea
count,32869.000000,32869.000000,11045.000000,28306.000000,28306.000000,32869.000000,32869.00000
mean,4.157556,5295.502297,1.634767,4.061846,132.055183,3326.950135,410.85281
std,0.384429,3744.362241,0.539851,0.639496,361.987164,2569.078801,213.41079
min,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.00000
25%,4.100000,2998.000000,1.000000,3.800000,7.000000,1404.000000,253.00000
50%,4.200000,4890.000000,2.000000,4.100000,34.000000,2754.000000,389.00000
75%,4.300000,6755.000000,2.000000,4.500000,125.000000,4642.000000,546.00000
max,4.900000,19388.000000,4.000000,5.000000,19391.000000,28728.000000,1885.00000

In [8]:
places_df.head()

,country,geometry,icon,id,ikea_address,ikea_location,ikea_place_id,ikea_rating,ikea_user_ratings_total,name,...,price_level,rating,reference,scope,type,types,user_ratings_total,vicinity,distance_to_ikea,duration_to_ikea
0,the Netherlands,"{'location': {'lat': 52.0097797, 'lng': 4.3917...",https://maps.gstatic.com/mapfiles/place_api/ic...,ae42128f873d1ed433826e1377ccdcb677c69e11,"Olof Palmestraat 1, 2616 LN Delft, Netherlands","{'lat': 52.01298449999999, 'lng': 4.3815153}",ChIJo6I07vC1xUcRZA27z1-1Q1c,4.2,11969,Taste Coffee,...,NaN,4.0,ChIJ840zcgnKxUcRNetK2uHnSww,GOOGLE,cafe,"['cafe', 'store', 'point_of_interest', 'food',...",2.0,"Graaf Willem II Laan 8, Delfgauw",2646,360
1,the Netherlands,"{'location': {'lat': 52.01090180000001, 'lng':...",https://maps.gstatic.com/mapfiles/place_api/ic...,72e194fe338e76aa519c7e33538930ecc700a487,"Olof Palmestraat 1, 2616 LN Delft, Netherlands","{'lat': 52.01298449999999, 'lng': 4.3815153}",ChIJo6I07vC1xUcRZA27z1-1Q1c,4.2,11969,De Nieuwe Prins,...,2.0,4.4,ChIJo88kSOm1xUcRlWe3_K81oY4,GOOGLE,cafe,"['cafe', 'point_of_interest', 'food', 'establi...",14.0,"Oosteinde 1-3, Delft",2227,410
2,the Netherlands,"{'location': {'lat': 52.0065033, 'lng': 4.3716...",https://maps.gstatic.com/mapfiles/place_api/ic...,0e1663ff496c39cfe6bc494abcb7ac619a53024d,"Olof Palmestraat 1, 2616 LN Delft, Netherlands","{'lat': 52.01298449999999, 'lng': 4.3815153}",ChIJo6I07vC1xUcRZA27z1-1Q1c,4.2,11969,the Bouwpub,...,1.0,4.6,ChIJw-2iwey1xUcReprW4owZ3u8,GOOGLE,cafe,"['cafe', 'point_of_interest', 'food', 'establi...",220.0,"Julianalaan 134, Delft",1745,337
3,the Netherlands,"{'location': {'lat': 52.006248, 'lng': 4.37133...",https://maps.gstatic.com/mapfiles/place_api/ic...,bba642eb2e52acc2b1adf919d1289f9f6b36933c,"Olof Palmestraat 1, 2616 LN Delft, Netherlands","{'lat': 52.01298449999999, 'lng': 4.3815153}",ChIJo6I07vC1xUcRZA27z1-1Q1c,4.2,11969,Espressobar Vascobello,...,NaN,3.0,ChIJEeM9A-21xUcRfOy3s3W8c6w,GOOGLE,cafe,"['cafe', 'store', 'point_of_interest', 'food',...",6.0,"Zuidplantsoen 6, Delft",1722,329
4,the Netherlands,"{'location': {'lat': 52.0130013, 'lng': 4.3656...",https://maps.gstatic.com/mapfiles/place_api/ic...,92c58753b772dff36d9bc255d2cd92a3b0caa4a1,"Olof Palmestraat 1, 2616 LN Delft, Netherlands","{'lat': 52.01298449999999, 'lng': 4.3815153}",ChIJo6I07vC1xUcRZA27z1-1Q1c,4.2,11969,CafÃ© 1Eighty,...,NaN,4.1,ChIJExYA-Oi1xUcRejXJldLWnbY,GOOGLE,cafe,"['cafe', 'point_of_interest', 'food', 'establi...",14.0,"Oranje Plantage 19, Delft",1870,331

In [9]:
import json

In [10]:
from ipyleaflet import Marker

center = (52.0097797, 4.3917406)

m = Map(center=center, zoom=5)

for ikea_id in places_df['ikea_place_id'].unique():
    places_subset = places_df.query("ikea_place_id=='%s'" % ikea_id)
    marker_tuple = tuple(
        Marker(location=[x for x in eval(geo)['location'].values()],
                          title=title, rise_on_hover=True) \
                    for geo,title in zip(places_subset['geometry'][:5], places_subset['name'][:5])
    )
    marker_cluster = MarkerCluster(markers = marker_tuple)
    
    m.add_layer(marker_cluster)
# marker = Marker(location=center, draggable=False)
# m.add_layer(layer_group);

In [11]:
from ipyleaflet import Marker

center = (52.0097797, 4.3917406)

# initialize map
m = Map(center=center, zoom=2)

# add markers for each ikea location
marker_group = [Marker(location=(eval(x)['lat'], eval(x)['lng']), draggable=False) \
                    for x in places_df['ikea_location'].unique()]
m.add_layer(LayerGroup(layers=marker_group))

# add controls
measure = MeasureControl(
    position='bottomleft',
    active_color = 'orange',
    primary_length_unit = 'kilometers'
)
m.add_control(measure)

m.add_control(FullScreenControl())

# show map
m

Map(basemap={'url': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 'max_zoom': 19, 'attribution': 'Map â€¦

# Number of IKEA's per country

You may be surprised that some big countries don't show more IKEA location (looking at you Sweden). But the Google Places API was restricted to return up to 20 results per country.

In [12]:
places_df.groupby('country')['ikea_location'].nunique()

country
Australia          11
Belgium             8
Canada             20
France             20
Germany            20
Hong Kong           5
Italy              20
Japan               6
Poland             20
Spain              13
Sweden             20
Taiwan              6
Turkey              7
the Netherlands    12
the UK             20
the US             20
Name: ikea_location, dtype: int64

# Shops around ikeas

We collected shops around IKEA's for our usecase. There are too many to visualize in leaflet at once, so as an example we'll plot 5 shops for every ikea location.

In [13]:
from ipyleaflet import Marker

center = (52.0097797, 4.3917406)

m = Map(center=center, zoom=5)

for ikea_id in places_df['ikea_place_id'].unique():
    places_subset = places_df.query("ikea_place_id=='%s'" % ikea_id)
    marker_tuple = tuple(
        Marker(location=[x for x in eval(geo)['location'].values()],
                          title=title, rise_on_hover=True) \
                    for geo,title in zip(places_subset['geometry'][:5], places_subset['name'][:5])
    )
    marker_cluster = MarkerCluster(markers = marker_tuple)
    
    m.add_layer(marker_cluster)

    # add controls
measure = MeasureControl(
    position='bottomleft',
    active_color = 'orange',
    primary_length_unit = 'kilometers'
)
m.add_control(measure)

m.add_control(FullScreenControl())

# show map
m

Map(basemap={'url': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 'max_zoom': 19, 'attribution': 'Map â€¦

# Choose an ikea and show all shops

In [14]:
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

def f(ikea_id):
    places_subset = places_df.query("ikea_place_id=='%s'" % ikea_id)
    
    center = eval(places_subset['ikea_location'].unique()[0])
    center_coords = (center['lat'], center['lng'])
    print(center)
    # initial map
    m = Map(center=center_coords, zoom=12)

    
    
#     marker_tuple = tuple(
#         Marker(location=[x for x in eval(geo)['location'].values()],
#                           title=title, rise_on_hover=True) \
#                     for geo,title in zip(places_subset['geometry'][:5], places_subset['name'][:5])
#     )
#     marker_cluster = MarkerCluster(markers = marker_tuple)
    
    marker_group = [Marker(location=[x for x in eval(geo)['location'].values()],
                          title=title, rise_on_hover=True) \
                    for geo,title in zip(places_subset['geometry'], places_subset['name'])]
    
    m.add_layer(LayerGroup(layers=marker_group))
    
    icon = Icon(icon_url='s/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAHkAvwMBEQACEQEDEQH/xAAbAAACAgMBAAAAAAAAAAAAAAABAgAFAwQHBv/EAEEQAAEDAwIDBAUJBgUFAAAAAAEAAgMEBTERMgYSIRNBcZMHUYHR0hQWNkJSYXORsRUiVbPB8DNjcpLhIyU1Q4L/xAAbAQEBAAIDAQAAAAAAAAAAAAAAAQQFAwYHAv/EADsRAAIBAgIECwUIAwEBAAAAAAABAgMEBREhMVHRBhITFRZBUnGBkbE0NVNhoRQiMkKCweHwcrLxQyX/2gAMAwEAAhEDEQA/APGS9y7QjrTEGR4oQeXKICtyPFANLuRAVu4KgMm8qIMjN4VAH71Chj3oAP3FAGPcgA7cVSBj3exQoHbj4qkGi3KMohyVQPGc+CjCEOVSDxd6hRFSDx7XKMoipDJHhRlQJfqogIMjxQDSbkQFGR4owNJuRADdyAMm4ogBm4IQj9yIoWbkYA/cUQDHuRgDtxREDHn2IyiuyUINFuRlFKoGj7/BRgUqkGjw5RlF71SDs2uUZRFSDx4UZQSdyiDFGQqAyZUQA3IVCGkyogxW7lWAv3IgwN3IwF+8qIAZuVYI/cUQCzcECA7cUDDHlAgO3FANHlRgQqgaPv8ABRgU5VIPHhyjKIqQdmHKMqEVBkjwowhZDhEVijI8VSDSZUQFGR4owNIeqIAbuRgj9xRAjdyoI/eVARm5UEfuKIEj3IAO3FANHu9ijArtx8VQNFuUYFOSqBo+/wAFGUUnqqQaP6yhRVSDx4cvlgx96+gZY8KMosncgEGQhBpMqIooyFSDSbkKBu4IAv3FEANygI/eUIRm5CkfuKEDHuQoHZKEDHlAB24oAx5QopyhB2d/gjKJ3oQaP6yFFQg7MOQCIDJHhCiyZCiBmt1DU3GpEFHH2kuhcG8wbqBnKxru8o2lPla8so7cn+xy0aFSvLi01my1fwlfSelvd5rPiWs6S4V8ZeT3GVzXd9j03gHCN+HU289P81nvV6SYU/8A2+j3Dmu7X5PTeUsoLZC05B0Oh1W7TzSaMFrJ5MtKHhy7VtPHVUlJ2sMg1a8SM693rWquMcw+2qulWqZSWtZPv2GXTw+4qRU4RzXgZncI34u1FvPms+JcHSXCvjLye4++a7vsem80rhaK61GP9oQdj2mvIC9p10zgrOs8Ttb3P7PPjZa9f7nBWtK1DLlFlmZKKwXS5Q/KKKkMsWpbzc7R1HiVx3WM2NnU5KvU4sss9T3H3SsbitHj045o2W8I34H/AMe7zWe9YvSXCvjLye45Oa7vsem81bnZLjbYxNXU/YscdG6yNJJ+4ArLs8Ws72bhbz4zXye44q1nWox41RZGvbKCpuNT2FFH2kobzcvMB09pXPeXtCzp8pXllHbk/wBjio0KleXFprNlkeEb8SSLefNZ71rukuFfGXk9xlc13fY9N5G8JX1p1Nvd5rPep0lwr4y8nuHNd32PTeQ8I34nX9nu81nvTpLhXxl5PcOa7vsem8w1fD11t1O+prKQxQs05ndo06anQYP3rItsbsLuqqNCpnJ9WT6tOzYcdWwuKMHOcckVJytoYhv2q01107UUEHbGMDn0c0aa4yfuKwr3ErWxy+0T4ueeWvq7sznoWtavnySzyNz5o37+Hu81nvWB0lwr4y8nuMjmq87H1W8ZvCV9Gv8A28+az3p0kwr4y8nuLzXedj6reYajhi80sEk9RRFkUbS57jIzoB7Vy0cfw6tUVOnVzk9CWT3HxPDrmEXKUcku7ealtoZK6V0cZa0Dc9x6DuCzrm6jbxzlm/ktf9/us4aFB1pZLQC4W+ShewPeyRj+rXsPQ494/NLa7hcJ8XQ1rT/vyfkK1u6WWbzTNePCyTgQr8ogeh9H/wBJIvw3/out8LPdc+9eptsG9qXczqa8lzO3gdtPgV9Q/Ej5lqZwt+5e+LqPPes6twJ9FqPxk/mOXkPCn3tV/T/qjuWE+xw8fVl+uv5myPHcbW2a63m00tOP3nNk5nabG6t1JXd+C99TsbG4r1dSa8Xk8kaLFbeVxWp04/P9j1NvoobfRxUlM3lijboPWfWT95XU728qXleVeq9L/uXcjbUKMaMFCC0IeqqIqWnkqKh4ZFG0ue44AC4aNKdaapwWbehHJOSinJ6jkHEF3lvVyfVyasjH7sERP+Gz3nJ/4XsWDYVDDbZU1pk9b+f8dR0u/vHc1M+paiz9Hn0jb+C/+iwOF3ux/wCSMnBfavBnUV5OztxiqqmGjppKmpeGQxN5nuPcPWuWhRqV6ipU1nJ6j4nNQWbKX56cO/xSL/a73LbdHsT+E/oY/wBtodorOKOIrRc+H6qChropZTyEM6gkB7ddNcrb8H8KvLXE6dStBpfe0/pewwMTuaVS1lGMs3o9Uc7OSvTWdV6zp/o+t3ySy/Knt0lqnc3/AMjoP6n2ryzhffcveqhF6Kay8Xr/AGR23BqHJ0OO9cvTqPTrqZtiIDHUwR1VPJBMNY5GFrh9xGi5revOhUjVhri8/I+KlNVIuMtTOR00sljuFTTztLix/I8tOhBadQ4f33r2WpGGI29OrTehrNbMnrT/ALrR0yE5WtWUJdX9zMF0uPy1zWsDgxp5i551c9xAGp9jR0XNaWn2fNt/LRqS06F5vSzjuLjlcsv+mmw9FmMxhX5RBnovR/8ASWIf5b/0XXOFnuufevU2uDe1eDOpryQ7eA4PgvuH4kfMtRwp2V73mee9Z1fgT6K0XjJ/McvIeFPvar+n/VHc8J9jh4+rL9dfNiLys7Tm0b2nLpr36LlUpcTi9Wf1PhpZ5jLjZ9lRxXa5LvZpaeF5bI0iRjdejy3rof7zotzgN9Tsr6NWovu6n8s+vw9DCxChKvQcIvScheCHEOBBB0IPcvZU81mjpD16T0vo7+kbfwX/ANF1jhd7rf8AkjbYL7V4M6gvKDtwHhpaQ/l5dOvMOi+oOSf3dZ8yyy0mHkpPswfkFkcrcZ/il5s+EqfyOb+kBrBxFo0AD5OzTQYyvTeCbcsNTlpfGl+x1XF9Fzo2IoLfSPr6+Clj6OmkDQR3es+wLf3dzG1oTry1RWZr6FJ1qigutna4ImQQshibysjaGtH3AaBeG1qsq1SVSWtvN+J3yEVCKitSK/iW5G1WWoqmEdqByQg97z0Hv9i2GD2DvruFHqb09y1nDd1+QpSmbNrrGXG309ZFtmjDtPsnvHsPRYt7bStbidGWuLaOSjUVWCmus2liHKc89I1uEFdFcI26NqG8khH2mjp+Y/Rel8Db7lLaVrJ6YaV3PX5P1Or43Q4tRVV1+p4td0NEOzCjKhX5UKei9H30li/Cf+i65ws91y716m0wb2rwZ1ReSnbwHB8F9w/Ej5lqOFHK97R56dX4E+itF4yfzHLyLhSv/rVf0/6o7nhXscPH1ZfrrxsTyXGF3fZb3aaxmrouSRk7Ad0ZLdfaMjwXbsCwyOI4fcU/zJpx78n66vqam+unb3FN9Tzz+h6uKWOaJksTw+N7Q5rgehBGoK6pOEoScZLJrQbSMlJJoZfJ9HOPSDZPklWLnTs/6FQdJQMMf6/b+vivTOCWLfaKH2So/vQ1fNfx6ZHV8Ys+JPlorQ9feavo6+kbfwH/ANFl8Lvdj/yRw4N7T4M6ivKDtxhraWCupJqSqZ2kEzCyRmpGoPgua3r1LerGrTeUlpR8VIKceKzz/wAweFv4SzzX+9brpPivxfpHcYnN9DY/N7zQ4l4Zs9p4dqprfRiORnIGntHO5dXjXTU9MlbfAcbv7vEadGtUzi+N1JflewwMRsqFO3lOMdOj1K/0bW/tq+e4Pb+7A3kZ/qdn8h+q2fDK95O2jbR1z0vuX85eRi4LQ41R1X1aDoq81OzlFe+LLbZaz5JVid8pYHkRR8wAOug19fRbvD8Cu76jytJLLPLSzBuL2jQlxZvSPYuJ7dfJ5IKPtmyRt5y2VnLqNdOnt/VfGJYLdYfTU6yWTeWgtteUa7cYMulpjNKvia3ftSzVFO0ay6c8f+odR+ePatxgV87K+hUb+7qfc92sw7+hy9vKPXuON66r2Y6Ox2YRlQHnqoDbtF0qbRWfK6NkLpg0tHbAlo1zghYOI2EL+g6E20m09HyMi1uHb1OOi6PH1/B2W/y3/Euv9DbLtS81uNnz3V2IHz+v56GO3eW/4kXA6yX5pea3DnqrsR5uV3NIXaBup10GAu2xWSSNK3m8y8tvGF3ttHFRUcdCIIgeXnY4u6nU6nm9ZK65fcGba9uJXFSUs5fNbMthtKGKToU1TitCNk8fX8fUt/lv+JYvQ2y7UvNbjm57q7EVl4v9dfDCbgymDodeQwtIz69SfUFt8KwejhqmqTbUtv8Awwry9ldZcZajat/GF4tlJHRUjaMwxDRnascTp+awr3gxaXdxKvNtOWxrcZFDFatKmoJajZHH1/P1Lf5b/iWL0Nsu1LzW45ee6uxGKq41vFVA+mqqe2ywydHtMb+o/wBy5rfgrbW1WNWnOSkvmtx8VMXnUi4yismVdoutVaKo1VFHCZS0tHagkAHwIW4xHD4YhQ5Go2lnnoyWrwMG1uXbVOPFFyeP7/rst/lv+JaDobZdqXmtxseequxEHH1/J05Lf5b/AIlehtj2pea3DnursRPn/f8A7Fv8t/xJ0Nsu1LzW4c91diNa48XXe7UclHWMoxDJoXdkxwd0II01PrCzLDg1a2NxG4pttrPW9qy2I4LjE6lem6bWhi2ziy6WmkFJQQ0TYmknWRji5xOSTzf3oriHB2hf13WrSlno61uJbYlO3pqEUjbHH1/P/rt/lv8AiWD0Nse1LzW4yOequxFFc7jUXSsfWVbYmzPA5uyBDTp07yV2PD7KFjbqhTehGsurh3FTlJGSz3WptFWauibC6bkLB2wJABzgj1L4xPDqeIUeRqNpZ56D6tbqVtPjxLgcf3/7Fv8ALf8AEtB0Nsu1LzW42PPdXYgjj6/6f4dv8t/xKdDbHtS81uHPVXYjztXUOq6iSofHHG+Q8zmxahupzoDhdptqPI0Y0s28llm9ZqKs+Um5ZZZiMwuY4wPygF70AzsogKMoAuyiBBlAR2UBBlAR25AQZQEduQEbuQEOUAWbkKA5VIFmVCilUgW96gAqBm4UAqoGZhRgVUDswoBX5QooQgz8oUUZQDPygA3KAj8oCNygI/KAjcoCOyhCM3IUBygCzKABygGjygF70AzO9AKUAzcIBUAzT0QCoB2YQCvyoAKkC/KhQDKoC/KAAygC7KADcqALsoANyqAuyhCM3IUBygCzcgAcoAt70AEAW96ACAZmEAqAZuFAIqB2YUAH5QCoAvygAMoAvygI3KAjsoCNygI7KAjcoCOygIzcgAcoAsygAcoBmZQClAFvegAgGbhAKgGbhAKgHZhAK7KFAhAuyhQDKEC5AAZQBKAAyhSHKEIMoUhyhAtyhQHKEC3KFAcoQLe9CgKEC1CgQgWlABAEIAIBmnohRXKAgQhHIUAyhAuyhQDKEC7KAjcoCOQEGUADlAEIUByhAt3IUCEC3vQoEIFqFAhBmoBSgC3CACAZuEKf/9k=',
                icon_size=[38, 95], icon_anchor=[22,94])
    mark = Marker(location=center, icon=icon, rotation_angle=90, rotation_origin='22px 94px')
    m.add_layer(mark);
    m.add_layer(Marker(location=center_coords, title=))

    # add controls
    measure = MeasureControl(
        position='bottomleft',
        active_color = 'orange',
        primary_length_unit = 'kilometers'
    )
    m.add_control(measure)

    m.add_control(FullScreenControl())

    # return map
    return(m)

In [15]:
interact(f, ikea_id=places_df['ikea_place_id'].unique());

interactive(children=(Dropdown(description='ikea_id', options=('ChIJo6I07vC1xUcRZA27z1-1Q1c', 'ChIJ0dxLWH--wEcâ€¦